server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TestDb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456

logging:
  level:
    com:
      jun:
        generator:
          jungenerator:
            mapper: debug